[build]
  publish = "__sapper__/export"
  command = "npm run export"

[[redirects]]
  from = "https://sekaicouk.netlify.com"
  to = "https://sekai.co.uk"
  status = 301
  force = true

  from = "https://sekai.co.uk/you"
  to = "https://you.sekai.co.uk"
  status = 301
  force = true